Modified
mrfourfour/horobito_spring_server pull request #2
Opened 2021-03-16 15:51 UTC by horobito

하...

2021-03-16 15:56 UTC, aerain requested changes

2021-03-16 15:56 UTC, aerain commented on src/main/java/com/example/demo/friend/controller/FriendShipController.java
> +        String result = friendShipService.dealWithFriendShip(friendId);
메소드의 결과값은 해당 도메인에 대한 값 객체를 반환시키도록 해야 합니다.
String은 해당 도메인에 대한 값을 평가하기엔 너무 추상적이어서 알기 힘드네요.

2021-03-16 15:56 UTC, aerain commented on src/main/java/com/example/demo/friend/domain/Friend.java
>  @Setter
`@Setter`가 외부에 열려있는 전략은 좋은 선택이 아닙니다.
누가 갑자기 님 팔 떼다가 강철의 연금술사마냥 무쇠 팔뚝 달아둔다고 생각하면 이해하기 편하겠네요.
적어도 해당 도메인 레이어에서만 수정할 수 있도록 Package-private정도로 접근제한자를 지정하면 좋을 것 같습니다.

2021-03-16 15:56 UTC, aerain commented on src/main/java/com/example/demo/friend/domain/Friend.java
> +    public Friend(FriendId friendId, FriendName friendname){
밑에 createFriend라는 정적 팩토리 메소드가 있는 것으로 보입니다.
정적 팩토리가 있을 경우에는 해당 생성자는 private등으로 외부에 노출 시키지 않는 전략을 취해야 합니다.

2021-03-16 15:56 UTC, aerain commented on src/main/java/com/example/demo/friend/domain/FriendId.java
> +@Setter
여거도 마찬가집니다.

2021-03-16 15:56 UTC, aerain commented on src/main/java/com/example/demo/friend/domain/FriendName.java
> +@Setter
마찬가지

2021-03-16 15:56 UTC, aerain commented on src/main/java/com/example/demo/friend/domain/Friendship.java
> +    public Friendship(User user, Friend friend){
요것도 private

2021-03-16 16:12 UTC, aerain commented on src/main/java/com/example/demo/friend/controller/FriendShipController.java
> +            return "200 OK";
```suggestion
ResponseEntity.ok()
```
문자열 그만쓰세요...

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Content.java
> +@Setter
항상 말하던거

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Content.java
> +@NoArgsConstructor
파라미터가 없는 생성자가 비즈니스에 필요한 게 아니라면 Protected로 제한자를 좁히는게 좋겠네요

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Feed.java
>      private Long likeNum;
Num이라는 명칭으로 이름에 등록하는거는 좋은 방법이 아닙니다. 자료형으로 표현해야합니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Feed.java
> +    public static Feed createFeed(Writer writer, Content contents) {
contents? content?

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/feed/service/CommentService.java
> +        Username username = Username.createUsername(authentication.getName());
이미 Username의 클래스의 팩토리 메소드이기 때문에 굳이 create**Username**이라는 suffix를 둘 필요는 없어보입니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/feed/service/FeedService.java
> +    public User findUserByAuthentication(){
By? From?

Authentication 을 파라미터로 받을것처럼 생겼는데 현재 메소드명으로는 그런게 잘 표현되어있지 않네요.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/controller/FriendShipController.java
> +    public List<FriendDto> getMyFriendList(@RequestParam(value="page") int page,
`getMyFriendList`

List 등의 자료구조에 대한 내용을 직접 표현하지 말아주세요. 비즈니스 특성에 따라 자료구조는 언제든지 바뀔 수 있습니다. 자료구조의 변경이 메소드명의 변경으로 전파되지 않게 해야합니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/controller/FriendShipController.java
> +    public void deleteFriendShipRequest(@PathVariable Long friendId){
`deleteFriendShip` 정도가 좋겠네요

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/domain/FriendShipRepository.java
> +    List<Friendship> findAllByUser(User user, Pageable pageable);
Pageable을 사용할거면 반환형은 `Page<Friendship>` 이 되어야 할 것 같습니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/service/FriendDto.java
> +@Getter
`@Value` 어노테이션을 사용할때는 `@Getter` 는 생략 가능합니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/service/FriendShipService.java
> +                .collect(Collectors.toList());
올 스트림 👍

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/service/FriendShipService.java
> +    public Result dealWithFriendShip(Long friendId) {
친구관계를 어떻게 처리하는걸까요? 친구를 추가한다? 친구를 삭제한다?
establish 나, 오히려 간단하게 create정도로 정해도 좋을것 같네요.

메소드명만 보고서는 이게 뭐하는 넘인지 잘 모를것 같습니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/friend/service/FriendShipService.java
> +    public Result dealWithFriendShip(Long friendId) {
Result는 이 도메인을 표현하기엔 너무 추상적인거 같네요
`FriendShipResult`나 아니면 좀더 이 친구 도메인을 잘 표현할 만한 결과정도로 표현하면 좋을 것 같습니다.

2021-03-18 15:34 UTC, aerain commented on src/main/java/com/example/demo/user/domain/UserBasicInfo.java
> +    public String getPasswordInfo(){
Info suffix를 굳이 붙여둔 이유가 있나요?

2021-03-19 12:16 UTC, horobito commented on src/main/java/com/example/demo/friend/controller/FriendShipController.java
> +    public void deleteFriendShipRequest(@PathVariable Long friendId){
여기까지 개선항목들 코드에 적용함

2021-03-19 12:20 UTC, horobito commented on src/main/java/com/example/demo/friend/domain/FriendShipRepository.java
> +    List<Friendship> findAllByUser(User user, Pageable pageable);
여기까지 개선항목들 코드에 적용함

2021-03-23 15:43 UTC, WonBeomChoi requested changes
통일 부탁드립니다 지금 우리나라 분단국가라고 로그인하고 회원가입 분단시켜놨는데 이게 민족정서에 맞는 코딩입니까?
현재 한국 정서에 맞는 개발 부탁드립니다.

2021-03-23 15:43 UTC, WonBeomChoi commented on src/main/java/com/example/demo/user/application/LoginRequest.java
> +package com.example.demo.user.application;
이거는 왜 application으로 해놨나요 signupRequest는 service에 있는데....
저 requestmapping어케하는지 보려고왔다가 레포지토리 구성 따라하려고했는데 망했네요 제 시간 물어내세요

2021-03-23 15:43 UTC, WonBeomChoi commented on src/main/java/com/example/demo/user/service/SignupRequest.java
> +package com.example.demo.user.service;
이거는 왜 service로 해놨나요 loginRequest는 application에 있는데....
저 requestmapping어케하는지 보려고왔다가 레포지토리 구성 따라하려고했는데 망했네요 제 시간 물어내세요..

2021-03-23 15:50 UTC, aerain commented
이거 각 객체들 단위테스트 짜보면 좋을거같네요 JUnit으로 작성해보시죠

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Feed.java
> +    @Column(name = "deleted")
동일 컬럼명의 경우 어노테이션 생략 가능합니다.

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Feed.java
> +    @JsonIgnoreProperties("feed")
표현층의 책임을 도메인 계층에 짊어지게하지 마세요

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Writer.java
> +    public static Writer create(User user) {
서로 다른 도메인 계층이 직접 서로 의존하지 않도록 하세요.

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Writer.java
> +    public static Writer create(User user) {
도메인 간 의존하는 대신 응용층에서 둘 사이의 결합을 하는게 좋겠네요

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/feed/service/CommentService.java
> +        Username username = Username.create("jihwan");
하드코딩..?

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/feed/service/CommentService.java
> +        Username username = Username.create("jihwan");
테스트코드로 작성하세요

2021-03-25 15:59 UTC, aerain commented on src/main/java/com/example/demo/friend/service/FriendShipService.java
> +        UserName username = UserName.create("jihwan");
여기도..

2021-03-27 14:16 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Preference.java
> +        this.preference ++;
내부적으로 필드를 ++ 한다면 preference를 사용하는 다른 스레드에서 데이터 불일치가 생길 수 있습니다.
내부 값 변경보다 새로운 값 객체를 생성하도록 하는게 좋을것 같습니다.

```java
public Preference like() {
    return new Preference(this.preference + 1);
}
```

2021-03-27 14:16 UTC, aerain commented on src/main/java/com/example/demo/feed/domain/Preference.java
> +    private Long preference = 0L;
preference가 not null 함이 보장되면 Long 타입보단 long 타입을 사용하는게 좋겠군요

2021-04-05 15:16 UTC, aerain commented
타임라인 구현은.. 다른 pr에서 ㅠㅠ

2021-04-05 15:17 UTC, aerain commented
테스트코드 먼저 짜라고했는데 왜 자꾸 구현만 하는겨...

2021-04-08 15:26 UTC, aerain commented on src/main/java/com/example/demo/friend/service/FriendShipService.java
> +    }
요런거는 책임을 다른 서비스에게 위임하면 어떨까요?
FriendshipService에서 해당 서비스를 모킹해서 원하는 Authentication을 반환하도록 stubbing 할 수 있습니다.

2021-04-09 14:29 UTC, merged